version: "3.9" 
services:
  db:
    image: mongo
    container_name: mongodb1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - "/home/macario/Escritorio/Sopes 1/SO1_Practica1_S12022/Volumenes:/data/db"
    networks:
      - practica1

  backend:
    image: amacario502/backend_p1_201905837
    container_name: backend1
    ports:
    - "4200:4200"
    restart: always
    depends_on:
    - db
    networks:
    - practica1

  frontend:
    image: amacario502/frontend_p1_201905837
    container_name: frontend1
    ports:
    - "80:80"
    restart: always
    depends_on:
    - backend
    networks:
    - practica1
  
volumes:
  mongodata:

networks:
  practica1:
    name: "practica1"
    driver: bridge